using Microsoft.EntityFrameworkCore;

namespace CasaDiFratelli.Api.Data;

public static class AdminSchemaBootstrapper
{
    public static async Task EnsureAsync(AppDbContext db)
    {
        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "Reservations" ADD COLUMN IF NOT EXISTS "BirthDate" date NULL;
            ALTER TABLE "Reservations" ADD COLUMN IF NOT EXISTS "CreatedByAdmin" boolean NOT NULL DEFAULT false;
            ALTER TABLE "Reservations" ADD COLUMN IF NOT EXISTS "InternalNote" text NULL;
            ALTER TABLE "Reservations" ADD COLUMN IF NOT EXISTS "IsArrived" boolean NOT NULL DEFAULT false;
            ALTER TABLE "Reservations" ADD COLUMN IF NOT EXISTS "IsBlacklisted" boolean NOT NULL DEFAULT false;
            ALTER TABLE "Reservations" ADD COLUMN IF NOT EXISTS "IsNoShow" boolean NOT NULL DEFAULT false;
            ALTER TABLE "Reservations" ADD COLUMN IF NOT EXISTS "IsRegularCustomer" boolean NOT NULL DEFAULT false;
            ALTER TABLE "Reservations" ADD COLUMN IF NOT EXISTS "MarketingConsent" boolean NOT NULL DEFAULT false;
            ALTER TABLE "Reservations" ADD COLUMN IF NOT EXISTS "OrderAccessToken" varchar(80) NULL;
            ALTER TABLE "Reservations" ADD COLUMN IF NOT EXISTS "PrivacyConsent" boolean NOT NULL DEFAULT false;
            CREATE INDEX IF NOT EXISTS "IX_Reservations_OrderAccessToken" ON "Reservations" ("OrderAccessToken");

            CREATE TABLE IF NOT EXISTS "BlacklistEntries" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "GuestName" text NULL,
                "Phone" text NULL,
                "Email" text NULL,
                "Reason" text NOT NULL,
                "Notes" text NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_BlacklistEntries" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "CustomerProfiles" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "GuestName" text NULL,
                "Phone" text NULL,
                "Email" text NULL,
                "ReservationCount" integer NOT NULL,
                "IsRegularCustomer" boolean NOT NULL,
                "BirthDate" date NULL,
                "MarketingConsent" boolean NOT NULL,
                "FirstReservationAtUtc" timestamp with time zone NOT NULL,
                "LastReservationAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_CustomerProfiles" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "MenuItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "NameBg" text NOT NULL,
                "NameEn" text NOT NULL,
                "DescriptionBg" text NOT NULL,
                "DescriptionEn" text NOT NULL,
                "Weight" text NOT NULL,
                "Price" numeric NOT NULL,
                "Category" text NOT NULL,
                "IsActive" boolean NOT NULL,
                "NotifySubscribers" boolean NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                "UpdatedAtUtc" timestamp with time zone NULL,
                CONSTRAINT "PK_MenuItems" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "AdminUsers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Name" varchar(120) NOT NULL,
                "Email" varchar(180) NOT NULL,
                "Role" text NOT NULL DEFAULT 'Manager',
                "PasswordHash" text NOT NULL,
                "PasswordSalt" text NOT NULL,
                "IsActive" boolean NOT NULL DEFAULT true,
                "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
                "LastLoginAtUtc" timestamp with time zone NULL,
                CONSTRAINT "PK_AdminUsers" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_AdminUsers_Email" ON "AdminUsers" ("Email");

            CREATE TABLE IF NOT EXISTS "AdminSessions" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "AdminUserId" integer NOT NULL,
                "TokenHash" varchar(128) NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
                "ExpiresAtUtc" timestamp with time zone NOT NULL,
                "RevokedAtUtc" timestamp with time zone NULL,
                "UserAgent" text NULL,
                "IpAddress" text NULL,
                CONSTRAINT "PK_AdminSessions" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_AdminSessions_TokenHash" ON "AdminSessions" ("TokenHash");

            CREATE TABLE IF NOT EXISTS "AdminDeviceCredentials" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "AdminUserId" integer NOT NULL,
                "Label" text NOT NULL DEFAULT '',
                "CredentialHash" varchar(128) NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
                "LastUsedAtUtc" timestamp with time zone NULL,
                "IsActive" boolean NOT NULL DEFAULT true,
                CONSTRAINT "PK_AdminDeviceCredentials" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_AdminDeviceCredentials_CredentialHash" ON "AdminDeviceCredentials" ("CredentialHash");

            CREATE TABLE IF NOT EXISTS "AuditLogs" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "AdminUserId" integer NULL,
                "AdminName" text NOT NULL DEFAULT '',
                "Action" text NOT NULL DEFAULT '',
                "Entity" text NOT NULL DEFAULT '',
                "EntityId" text NOT NULL DEFAULT '',
                "BeforeJson" text NULL,
                "AfterJson" text NULL,
                "IpAddress" text NULL,
                "UserAgent" text NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "DiningOrders" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ReservationId" integer NOT NULL,
                "GuestName" varchar(120) NOT NULL DEFAULT '',
                "TableLabel" varchar(120) NOT NULL DEFAULT '',
                "Status" varchar(30) NOT NULL DEFAULT 'New',
                "TotalPrice" numeric NOT NULL DEFAULT 0,
                "Notes" text NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "PK_DiningOrders" PRIMARY KEY ("Id")
            );

            CREATE INDEX IF NOT EXISTS "IX_DiningOrders_ReservationId" ON "DiningOrders" ("ReservationId");

            CREATE TABLE IF NOT EXISTS "DiningOrderItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "DiningOrderId" integer NOT NULL,
                "MenuItemId" integer NULL,
                "Name" varchar(180) NOT NULL DEFAULT '',
                "UnitPrice" numeric NOT NULL DEFAULT 0,
                "Quantity" integer NOT NULL DEFAULT 1,
                "Notes" text NULL,
                CONSTRAINT "PK_DiningOrderItems" PRIMARY KEY ("Id")
            );

            CREATE INDEX IF NOT EXISTS "IX_DiningOrderItems_DiningOrderId" ON "DiningOrderItems" ("DiningOrderId");

            ALTER TABLE "BlacklistEntries" ADD COLUMN IF NOT EXISTS "GuestName" text NULL;
            ALTER TABLE "BlacklistEntries" ADD COLUMN IF NOT EXISTS "Phone" text NULL;
            ALTER TABLE "BlacklistEntries" ADD COLUMN IF NOT EXISTS "Email" text NULL;
            ALTER TABLE "BlacklistEntries" ADD COLUMN IF NOT EXISTS "Reason" text NOT NULL DEFAULT '';
            ALTER TABLE "BlacklistEntries" ADD COLUMN IF NOT EXISTS "Notes" text NULL;
            ALTER TABLE "BlacklistEntries" ADD COLUMN IF NOT EXISTS "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now();

            ALTER TABLE "CustomerProfiles" ADD COLUMN IF NOT EXISTS "GuestName" text NULL;
            ALTER TABLE "CustomerProfiles" ADD COLUMN IF NOT EXISTS "Phone" text NULL;
            ALTER TABLE "CustomerProfiles" ADD COLUMN IF NOT EXISTS "Email" text NULL;
            ALTER TABLE "CustomerProfiles" ADD COLUMN IF NOT EXISTS "ReservationCount" integer NOT NULL DEFAULT 0;
            ALTER TABLE "CustomerProfiles" ADD COLUMN IF NOT EXISTS "IsRegularCustomer" boolean NOT NULL DEFAULT false;
            ALTER TABLE "CustomerProfiles" ADD COLUMN IF NOT EXISTS "BirthDate" date NULL;
            ALTER TABLE "CustomerProfiles" ADD COLUMN IF NOT EXISTS "MarketingConsent" boolean NOT NULL DEFAULT false;
            ALTER TABLE "CustomerProfiles" ADD COLUMN IF NOT EXISTS "FirstReservationAtUtc" timestamp with time zone NOT NULL DEFAULT now();
            ALTER TABLE "CustomerProfiles" ADD COLUMN IF NOT EXISTS "LastReservationAtUtc" timestamp with time zone NOT NULL DEFAULT now();

            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "NameBg" text NOT NULL DEFAULT '';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "NameEn" text NOT NULL DEFAULT '';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "DescriptionBg" text NOT NULL DEFAULT '';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "DescriptionEn" text NOT NULL DEFAULT '';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "Weight" text NOT NULL DEFAULT '';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "Price" numeric NOT NULL DEFAULT 0;
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "Category" text NOT NULL DEFAULT 'Main';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "IsActive" boolean NOT NULL DEFAULT true;
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "NotifySubscribers" boolean NOT NULL DEFAULT false;
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now();
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "UpdatedAtUtc" timestamp with time zone NULL;

            ALTER TABLE "DiningOrders" ADD COLUMN IF NOT EXISTS "ReservationId" integer NOT NULL DEFAULT 0;
            ALTER TABLE "DiningOrders" ADD COLUMN IF NOT EXISTS "GuestName" varchar(120) NOT NULL DEFAULT '';
            ALTER TABLE "DiningOrders" ADD COLUMN IF NOT EXISTS "TableLabel" varchar(120) NOT NULL DEFAULT '';
            ALTER TABLE "DiningOrders" ADD COLUMN IF NOT EXISTS "Status" varchar(30) NOT NULL DEFAULT 'New';
            ALTER TABLE "DiningOrders" ADD COLUMN IF NOT EXISTS "TotalPrice" numeric NOT NULL DEFAULT 0;
            ALTER TABLE "DiningOrders" ADD COLUMN IF NOT EXISTS "Notes" text NULL;
            ALTER TABLE "DiningOrders" ADD COLUMN IF NOT EXISTS "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now();

            ALTER TABLE "DiningOrderItems" ADD COLUMN IF NOT EXISTS "DiningOrderId" integer NOT NULL DEFAULT 0;
            ALTER TABLE "DiningOrderItems" ADD COLUMN IF NOT EXISTS "MenuItemId" integer NULL;
            ALTER TABLE "DiningOrderItems" ADD COLUMN IF NOT EXISTS "Name" varchar(180) NOT NULL DEFAULT '';
            ALTER TABLE "DiningOrderItems" ADD COLUMN IF NOT EXISTS "UnitPrice" numeric NOT NULL DEFAULT 0;
            ALTER TABLE "DiningOrderItems" ADD COLUMN IF NOT EXISTS "Quantity" integer NOT NULL DEFAULT 1;
            ALTER TABLE "DiningOrderItems" ADD COLUMN IF NOT EXISTS "Notes" text NULL;

            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'MenuItems'
                    AND column_name = 'CreatedAtUtc'
                    AND data_type = 'text'
                ) THEN
                    ALTER TABLE "MenuItems"
                    ALTER COLUMN "CreatedAtUtc" TYPE timestamp with time zone
                    USING COALESCE(NULLIF("CreatedAtUtc", '')::timestamp with time zone, now());
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'MenuItems'
                    AND column_name = 'UpdatedAtUtc'
                    AND data_type = 'text'
                ) THEN
                    ALTER TABLE "MenuItems"
                    ALTER COLUMN "UpdatedAtUtc" TYPE timestamp with time zone
                    USING NULLIF("UpdatedAtUtc", '')::timestamp with time zone;
                END IF;
            END $$;
            """);
    }
}
