BEGIN;

CREATE TABLE IF NOT EXISTS "MenuItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NameBg" text NOT NULL,
    "NameEn" text NOT NULL,
    "DescriptionBg" text NOT NULL,
    "DescriptionEn" text NOT NULL,
    "Weight" text NOT NULL,
    "Price" numeric NOT NULL,
    "Category" text NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "NotifySubscribers" boolean NOT NULL DEFAULT false,
    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAtUtc" timestamp with time zone NULL,
    CONSTRAINT "PK_MenuItems" PRIMARY KEY ("Id")
);

ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "NameBg" text NOT NULL DEFAULT '';
ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "NameEn" text NOT NULL DEFAULT '';
ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "DescriptionBg" text NOT NULL DEFAULT '';
ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "DescriptionEn" text NOT NULL DEFAULT '';
ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "Weight" text NOT NULL DEFAULT '';
ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "Price" numeric NOT NULL DEFAULT 0;
ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "Category" text NOT NULL DEFAULT 'Main';
ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "IsActive" boolean NOT NULL DEFAULT true;
ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "NotifySubscribers" boolean NOT NULL DEFAULT false;
ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now();
ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "UpdatedAtUtc" timestamp with time zone NULL;

ALTER TABLE "Reservations" ADD COLUMN IF NOT EXISTS "PrivacyConsent" boolean NOT NULL DEFAULT false;

INSERT INTO "MenuItems"
("Category", "NameBg", "NameEn", "DescriptionBg", "DescriptionEn", "Weight", "Price", "IsActive", "NotifySubscribers", "CreatedAtUtc")
SELECT data."Category", data."NameBg", data."NameEn", data."DescriptionBg", data."DescriptionEn", data."Weight", data."Price", true, data."NotifySubscribers", now()
FROM (
    VALUES
    ('salads', 'Салата Dei Fratelli', 'Dei Fratelli Salad', 'Със запечено козе сирене, лоло росо, рукола, бейби спанак, круша, орех пекан и малинов хайвер', 'Baked goat cheese, lollo rosso, arugula, baby spinach, pear, pecan, and raspberry caviar', '300 гр', 18.60::numeric, false),
    ('salads', 'Салата от бурата', 'Burrata Salad', 'Чери домати, кедрови ядки, рукола, песто и домашна фокача', 'Cherry tomatoes, pine nuts, arugula, pesto, and homemade focaccia', '360 гр', 19.56::numeric, false),
    ('salads', 'Салата Цезар с пиле', 'Chicken Caesar Salad', 'Айсберг, пилешко филе, чери домати, пармезан, билкови крутони и сос Цезар', 'Iceberg lettuce, chicken fillet, cherry tomatoes, parmesan, croutons, and Caesar dressing', '380 гр', 18.78::numeric, false),
    ('salads', 'Салата със сотирани тигрови скариди', 'Tiger Shrimp Salad', 'Микс зелени салати, жулиени зеленчуци и дресинг песто', 'Mixed green salads, julienne vegetables, and pesto dressing', '350 гр', 21.32::numeric, false),
    ('salads', 'Салата Фермата', 'Farm Salad', 'Панирано фермерско сирене, сезонни плодове, меден дресинг, сос от нар и бейби спанак', 'Breaded farm cheese, seasonal fruit, honey dressing, pomegranate sauce, and baby spinach', '350 гр', 18.60::numeric, false),
    ('starters', 'Антипасти за двама', 'Antipasti for Two', 'Плато от италиански колбаси, маслини каламата, сирена и изпечена фокача', 'Italian cold cuts, Kalamata olives, cheeses, and baked focaccia', '300 гр', 27.38::numeric, false),
    ('starters', 'Трио разядки с домашен хляб', 'Trio of Spreads with Homemade Bread', 'Тирокафтери, катък с чушка и млечна салата', 'Tirokafteri, katak with pepper, and milk salad', '300 гр', 15.45::numeric, false),
    ('starters', 'Патешки сърца с печурки', 'Duck Hearts with Mushrooms', 'Топло предястие с наситен вкус', 'Warm starter with a rich flavor', '300 гр', 17.90::numeric, false),
    ('starters', 'Бейби калмари с манго сос', 'Baby Calamari with Mango Sauce', 'Крехки калмари с плодов акцент', 'Tender calamari with a fruity accent', '280 гр', 21.91::numeric, false),
    ('starters', 'Скариди темпура', 'Tempura Shrimp', 'Поднесени с чипотле сос', 'Served with chipotle sauce', '250 гр', 21.32::numeric, false),
    ('starters', 'Телешки език с манатарка и скаморца', 'Beef Tongue with Porcini and Scamorza', 'Богат вкус и кремообразен завършек', 'Deep savory flavor with creamy finish', '330 гр', 21.32::numeric, false),
    ('pasta-risotto', 'Ризото с диви гъби и трюфел', 'Wild Mushroom and Truffle Risotto', 'Кладница, манатарка и пармезан', 'Oyster mushrooms, porcini, and parmesan', '360 гр', 19.36::numeric, false),
    ('pasta-risotto', 'Ризото с рибай “Талиата”', 'Ribeye Tagliata Risotto', 'Signature dish by Chef Yurukov — ризото с шафран, рибай, спанак и чипс от пармезан', 'Signature dish by Chef Yurukov — saffron risotto, ribeye, spinach, and parmesan chips', '380 гр', 29.14::numeric, true),
    ('pasta-risotto', 'Талиателе песто и скариди', 'Pesto Tagliatelle with Shrimp', 'Босилеково песто, зехтин, пармезан, шамфъстък и скариди', 'Basil pesto, olive oil, parmesan, pistachio, and shrimp', '400 гр', 21.31::numeric, false),
    ('pasta-risotto', 'Талиатели с пистачио и панчета', 'Tagliatelle with Pistachio and Pancetta', 'Signature dish by Chef Yurukov — домашна паста с крем от шамфъстък и панчета', 'Signature dish by Chef Yurukov — homemade pasta with pistachio cream and pancetta', '400 гр', 19.17::numeric, true),
    ('pasta-risotto', 'Талиатели Болонезе', 'Tagliatelle Bolognese', 'Домашна паста с телешка кайма и пармезан', 'Homemade pasta with minced beef and parmesan', '400 гр', 17.62::numeric, false),
    ('pasta-risotto', 'Талиателе Карбонара', 'Tagliatelle Carbonara', 'Домашна паста, панчета и класически сос от жълтък и грана падано', 'Homemade pasta, pancetta, and classic egg yolk and Grana Padano sauce', '400 гр', 19.38::numeric, false),
    ('mains', 'Нашите свински ребра с BBQ сос', 'BBQ Pork Ribs', 'Бавно готвени ребра, глазирани с BBQ сос и бейби картофки', 'Slow-cooked ribs glazed with BBQ sauce and baby potatoes', '450 гр', 28.95::numeric, false),
    ('mains', 'Шницел от сочни пилешки гърди', 'Chicken Schnitzel', 'Поднесен с картофи соте и пармезан', 'Served with sauteed potatoes and parmesan', '400 гр', 22.69::numeric, false),
    ('mains', 'Телешки кюфтенца Black Angus', 'Black Angus Beef Meatballs', 'С опушен катък, домашна лютеница и фокача', 'With smoked katak, homemade lutenitsa, and focaccia', '400 гр', 21.51::numeric, false),
    ('mains', 'Рибай стек Black Angus', 'Black Angus Ribeye Steak', 'Зрял аржентински рибай с бейби картофки, аспержи и сос по избор', 'Aged Argentine ribeye with baby potatoes, asparagus, and sauce of choice', '450 гр', 62.59::numeric, false),
    ('mains', 'Филе от лаврак', 'Sea Bass Fillet', 'С картофено пюре, броколи и beurre blanc сос', 'With mashed potatoes, broccoli, and beurre blanc sauce', '400 гр', 25.23::numeric, false),
    ('mains', 'Филе от сьомга със задушени зеленчуци', 'Salmon Fillet with Steamed Vegetables', 'Бейби моркови, аспержи, тиквички и сос холандез', 'Baby carrots, asparagus, zucchini, and hollandaise sauce', '350 гр', 26.40::numeric, false),
    ('pizza', 'Маргарита', 'Margherita', 'Доматен сос, моцарела, риган и босилек', 'Tomato sauce, mozzarella, oregano, and basil', '400 гр', 13.91::numeric, false),
    ('pizza', 'Прошуто фунги', 'Prosciutto Funghi', 'Доматен сос, моцарела, гъби, кото и риган', 'Tomato sauce, mozzarella, mushrooms, cotto, and oregano', '450 гр', 17.41::numeric, false),
    ('pizza', 'Капричоза', 'Capricciosa', 'Доматен сос, моцарела, маслини каламата, артишок, кото и гъби', 'Tomato sauce, mozzarella, Kalamata olives, artichoke, cotto, and mushrooms', '500 гр', 19.36::numeric, false),
    ('pizza', 'Куатро формаджи', 'Quattro Formaggi', 'Сметана, моцарела, горгонзола, бри, пармезан и чери домати', 'Cream, mozzarella, gorgonzola, brie, parmesan, and cherry tomatoes', '450 гр', 17.40::numeric, false),
    ('pizza', 'Прошуто крудо', 'Prosciutto Crudo', 'Доматен сос, моцарела, крудо, рукола, чери домати и пармезан', 'Tomato sauce, mozzarella, crudo, arugula, cherry tomatoes, and parmesan', '450 гр', 21.32::numeric, false),
    ('pizza', 'Джорджио', 'Giorgio', 'Моцарела, кото, шамфъстък, песто, бурата, босилек и лимонови кори', 'Mozzarella, cotto, pistachio, pesto, burrata, basil, and lemon zest', '500 гр', 23.27::numeric, false),
    ('bread', 'Цял домашен хляб', 'Whole Homemade Bread', 'Прясно изпечен домашен хляб', 'Freshly baked homemade bread', '450 гр', 11.54::numeric, false),
    ('bread', 'Фокача на парче', 'Focaccia Slice', 'Класическа фокача', 'Classic focaccia', '150 гр', 5.67::numeric, false),
    ('bread', 'Домашна питка с Филаделфия', 'Homemade Bread Roll with Philadelphia', 'Мека питка с крема сирене', 'Soft bread roll with cream cheese', '250 гр', 7.63::numeric, false),
    ('bread', 'Комбинирана пърленка със сирене и кашкавал', 'Flatbread with White and Yellow Cheese', 'Богат вкус и аромат', 'Rich taste and aroma', '350 гр', 7.63::numeric, false),
    ('desserts', 'Пистачио чийзкейк', 'Pistachio Cheesecake', 'Кремообразен десерт с шамфъстък', 'Creamy pistachio dessert', '150 гр', 11.45::numeric, false),
    ('desserts', 'Тирамису', 'Tiramisu', 'Класически италиански десерт', 'Classic Italian dessert', '200 гр', 10.95::numeric, false),
    ('desserts', 'Шоколадов мус by Chef Yurukov', 'Chocolate Mousse by Chef Yurukov', 'Авторски шоколадов финал', 'Signature chocolate finish', '170 гр', 12.01::numeric, true),
    ('desserts', 'Шоколадово суфле със сметанов сладолед', 'Chocolate Souffle with Cream Ice Cream', 'Топъл десерт с кремообразен център', 'Warm dessert with a creamy center', '150 гр', 10.17::numeric, false)
) AS data("Category", "NameBg", "NameEn", "DescriptionBg", "DescriptionEn", "Weight", "Price", "NotifySubscribers")
WHERE NOT EXISTS (
    SELECT 1
    FROM "MenuItems" existing
    WHERE lower(existing."NameBg") = lower(data."NameBg")
);

COMMIT;
