using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CasaDiFratelli.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddDiningOrders : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "Reservations"
                ADD COLUMN IF NOT EXISTS "OrderAccessToken" character varying(80) NULL;

                CREATE INDEX IF NOT EXISTS "IX_Reservations_OrderAccessToken"
                ON "Reservations" ("OrderAccessToken");

                CREATE TABLE IF NOT EXISTS "DiningOrders" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "ReservationId" integer NOT NULL,
                    "GuestName" character varying(120) NOT NULL,
                    "TableLabel" character varying(120) NOT NULL,
                    "Status" character varying(30) NOT NULL DEFAULT 'New',
                    "TotalPrice" numeric NOT NULL DEFAULT 0,
                    "Notes" text NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "PK_DiningOrders" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_DiningOrders_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES "Reservations" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_DiningOrders_ReservationId"
                ON "DiningOrders" ("ReservationId");

                CREATE TABLE IF NOT EXISTS "DiningOrderItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "DiningOrderId" integer NOT NULL,
                    "MenuItemId" integer NULL,
                    "Name" character varying(180) NOT NULL,
                    "UnitPrice" numeric NOT NULL DEFAULT 0,
                    "Quantity" integer NOT NULL DEFAULT 1,
                    "Notes" text NULL,
                    CONSTRAINT "PK_DiningOrderItems" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_DiningOrderItems_DiningOrders_DiningOrderId" FOREIGN KEY ("DiningOrderId") REFERENCES "DiningOrders" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_DiningOrderItems_DiningOrderId"
                ON "DiningOrderItems" ("DiningOrderId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "DiningOrderItems";
                DROP TABLE IF EXISTS "DiningOrders";
                DROP INDEX IF EXISTS "IX_Reservations_OrderAccessToken";
                ALTER TABLE "Reservations" DROP COLUMN IF EXISTS "OrderAccessToken";
                """);
        }
    }
}
