using CasaDiFratelli.Api.Data;
using CasaDiFratelli.Api.Models;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CasaDiFratelli.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class BlacklistController : ControllerBase
{
    private readonly AppDbContext _db;
    private readonly ILogger<BlacklistController> _logger;

    public BlacklistController(AppDbContext db, ILogger<BlacklistController> logger)
    {
        _db = db;
        _logger = logger;
    }

    private static void AddParameter(IDbCommand command, string name, object? value)
    {
        var parameter = command.CreateParameter();
        parameter.ParameterName = name;
        parameter.Value = value ?? DBNull.Value;
        command.Parameters.Add(parameter);
    }

    private async Task EnsureConnectionOpenAsync()
    {
        var connection = _db.Database.GetDbConnection();

        if (connection.State != ConnectionState.Open)
        {
            await connection.OpenAsync();
        }
    }

    private async Task EnsureBlacklistStorageAsync()
    {
        await EnsureConnectionOpenAsync();

        await using var command = _db.Database.GetDbConnection().CreateCommand();
        command.CommandText = """
            CREATE TABLE IF NOT EXISTS "BlacklistEntries" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "GuestName" text NULL,
                "Phone" text NULL,
                "Email" text NULL,
                "Reason" text NOT NULL DEFAULT '',
                "Notes" text NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "PK_BlacklistEntries" PRIMARY KEY ("Id")
            );

            ALTER TABLE "BlacklistEntries" ADD COLUMN IF NOT EXISTS "GuestName" text NULL;
            ALTER TABLE "BlacklistEntries" ADD COLUMN IF NOT EXISTS "Phone" text NULL;
            ALTER TABLE "BlacklistEntries" ADD COLUMN IF NOT EXISTS "Email" text NULL;
            ALTER TABLE "BlacklistEntries" ADD COLUMN IF NOT EXISTS "Reason" text NOT NULL DEFAULT '';
            ALTER TABLE "BlacklistEntries" ADD COLUMN IF NOT EXISTS "Notes" text NULL;
            ALTER TABLE "BlacklistEntries" ADD COLUMN IF NOT EXISTS "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now();
            """;

        await command.ExecuteNonQueryAsync();
    }

    [HttpGet]
    public async Task<IActionResult> Get()
    {
        try
        {
            await EnsureBlacklistStorageAsync();

            await using var command = _db.Database.GetDbConnection().CreateCommand();
            command.CommandText = """
                SELECT
                    "Id",
                    "GuestName",
                    "Phone",
                    "Email",
                    "Reason",
                    "Notes",
                    "CreatedAtUtc"::text
                FROM "BlacklistEntries"
                ORDER BY "CreatedAtUtc" DESC, "Id" DESC;
                """;

            var list = new List<object>();
            await using var reader = await command.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                list.Add(new
                {
                    Id = reader.GetInt32(0),
                    GuestName = reader.IsDBNull(1) ? null : reader.GetString(1),
                    Phone = reader.IsDBNull(2) ? null : reader.GetString(2),
                    Email = reader.IsDBNull(3) ? null : reader.GetString(3),
                    Reason = reader.IsDBNull(4) ? string.Empty : reader.GetString(4),
                    Notes = reader.IsDBNull(5) ? null : reader.GetString(5),
                    CreatedAtUtc = reader.IsDBNull(6) ? null : reader.GetString(6)
                });
            }

            return Ok(list);
        }
        catch (Exception error)
        {
            _logger.LogError(error, "Failed to load blacklist entries.");
            return StatusCode(500, new { message = "Failed to load blacklist entries.", detail = error.Message });
        }
    }

    [HttpPost]
    public async Task<IActionResult> Add([FromBody] BlacklistEntry entry)
    {
        try
        {
            await EnsureBlacklistStorageAsync();

            entry.GuestName = entry.GuestName?.Trim();
            entry.Phone = entry.Phone?.Trim();
            entry.Email = entry.Email?.Trim();
            entry.Reason = string.IsNullOrWhiteSpace(entry.Reason) ? "Manual review" : entry.Reason.Trim();
            entry.Notes = entry.Notes?.Trim();

            await using var command = _db.Database.GetDbConnection().CreateCommand();
            command.CommandText = """
                INSERT INTO "BlacklistEntries"
                ("GuestName", "Phone", "Email", "Reason", "Notes", "CreatedAtUtc")
                VALUES
                (@guestName, @phone, @email, @reason, @notes, now())
                RETURNING "Id";
                """;
            AddParameter(command, "@guestName", entry.GuestName);
            AddParameter(command, "@phone", entry.Phone);
            AddParameter(command, "@email", entry.Email);
            AddParameter(command, "@reason", entry.Reason);
            AddParameter(command, "@notes", entry.Notes);

            entry.Id = Convert.ToInt32(await command.ExecuteScalarAsync());

            return Ok(new
            {
                entry.Id,
                entry.GuestName,
                entry.Phone,
                entry.Email,
                entry.Reason,
                entry.Notes
            });
        }
        catch (Exception error)
        {
            _logger.LogError(error, "Failed to add blacklist entry.");
            return StatusCode(500, new { message = "Failed to add blacklist entry.", detail = error.Message });
        }
    }

    [HttpDelete("{id}")]
    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            await EnsureBlacklistStorageAsync();

            await using var command = _db.Database.GetDbConnection().CreateCommand();
            command.CommandText = """
                DELETE FROM "BlacklistEntries"
                WHERE "Id" = @id;
                """;
            AddParameter(command, "@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows == 0)
                return NotFound();

            return Ok();
        }
        catch (Exception error)
        {
            _logger.LogError(error, "Failed to delete blacklist entry.");
            return StatusCode(500, new { message = "Failed to delete blacklist entry.", detail = error.Message });
        }
    }
}
